"use client";

import { useState } from "react";
import { ArrowRight, Check, Send, Sparkles, X } from "lucide-react";

export type CoachAction = { type:"navigate"; page:string } | { type:"add_habit"; title:string; detail:string } | { type:"add_event"; title:string; date:string; time:string; category:string } | { type:"add_food"; name:string; amount:string; date:string; calories:number; protein:number; carbs:number; fats:number } | { type:"log_weight"; date:string; weight:number } | { type:"exercise_burn"; date:string; calories:number };
type Action = CoachAction;
type Message = { role:"assistant"|"user"; text:string; proposal?:Action|null };
const describe=(a:Action)=>a.type==="navigate"?`Open ${a.page}`:a.type==="add_habit"?`Add habit “${a.title}”${a.detail?` · ${a.detail}`:""}`:a.type==="add_event"?`Add “${a.title}” to your planner on ${a.date} at ${a.time}`:a.type==="add_food"?`Log ${a.name} on ${a.date} · ${a.calories} kcal, P ${a.protein}g / C ${a.carbs}g / F ${a.fats}g`:a.type==="log_weight"?`Log ${a.weight} kg on ${a.date}`:`Set exercise burn to ${a.calories} kcal on ${a.date}`;

export function CoachAssistant({context,onApprove}:{context:Record<string,unknown>;onApprove:(action:Action)=>void}) {
  const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Hi Madhvendra — I can review the tracking details shown in PULSE, help calculate a workout or nutrition starting point, and suggest changes. I’ll ask you to approve every change before applying it."}]);
  const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const send=async()=>{const message=input.trim();if(!message||busy)return;setInput("");setError("");const next=[...messages,{role:"user" as const,text:message}];setMessages(next);setBusy(true);try{const res=await fetch("/api/coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,context}),cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not reach the coach.");setMessages(v=>[...v,{role:"assistant",text:data.reply,proposal:data.proposal??null}]);}catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}};
  const approve=(index:number,action:Action)=>{onApprove(action);setMessages(v=>v.map((m,i)=>i===index?{...m,proposal:null,text:`${m.text}\n\nDone — I applied that change.`}:m));};
  const dismiss=(index:number)=>setMessages(v=>v.map((m,i)=>i===index?{...m,proposal:null,text:`${m.text}\n\nNo change made.`}:m));
  return <section className="coach-assistant panel"><div className="coach-assistant-head"><span className="coach-assistant-icon"><Sparkles size={17}/></span><div><strong>PULSE Coach</strong><small>Private session · changes always need your approval</small></div><span className="coach-online"><i/> READY</span></div><div className="coach-thread" aria-live="polite">{messages.map((m,i)=><article key={i} className={`coach-message ${m.role}`}><p>{m.text}</p>{m.proposal&&<div className="coach-proposal"><span className="eyebrow">PROPOSED CHANGE</span><b>{describe(m.proposal)}</b><div><button className="secondary-btn" onClick={()=>dismiss(i)}><X size={13}/> Decline</button><button className="primary-btn" onClick={()=>approve(i,m.proposal!)}><Check size={14}/> Approve change</button></div></div>}</article>)}{busy&&<div className="coach-message assistant coach-thinking"><span/><span/><span/> Thinking through your request…</div>}</div><form className="coach-compose" onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="coach-prompt">Ask PULSE Coach</label><textarea id="coach-prompt" rows={2} maxLength={1200} value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about today’s calories, a workout split, or say ‘add a habit…’" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}}/><button className="primary-btn" disabled={busy||!input.trim()} aria-label="Send message"><Send size={15}/><span>Send</span></button></form>{error&&<p className="coach-error" role="alert">{error}</p>}<small className="coach-disclaimer">Health calculations are estimates, not medical advice. Review every proposed entry before approval.</small></section>;
}
